# Generated by Django 6.0 on 2025-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
