# Generated by Django 6.0 on 2025-12-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacher1',
        ),
    ]
