# Generated by Django 6.0 on 2025-12-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_teacher_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(blank=True, max_length=100)),
                ('num_students', models.IntegerField(default=0)),
            ],
        ),
    ]
